language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: JGVJuVx0A+GoqXGyobPC3ye++lZrOZtV7+c2qegQ+BdwfIrsUW9CIRg+Dq+hgPDDMUl2cU5KYtv5OEkklaMw4dQTLKyuD4FtT2aOCKbmgonYsawbD1dY8svuqhdzUpl+RpDTjh7OILAhGR1xGM7/7ogXwRiKqb+blu/mq/BjApckTm5HbIoCy4N41cMZhUzjzX5R+HIwn4Pajp1QKWiETXuIqtjEtkQosgtzD5mdo/tOKxQVCHnnvnVBwPF518JfQ4Qv49uUzYyErLn4IZ7/h8cPjR+usS61wmGGD04HVvBs98iAlPP11ncYprAEnd61m4q054oeesycKTy554maK56M9Lkgfii1HzT2abKZQx+MmzcJys8Fq97YR+frA+DS0LsTbYxXqZ6QPIkKDGC9tMl/BABXZkMQWfE2NAgEW3VhnPNGztEGTzZfCl9jVAVZ2biqbVmnjd9iAAfT0ZWycqzu5LkepfwOOBb3jSizsYPTxGVJBhhMHaNsa2WY5syDiM6hJbHSMNJ7bv1j3z3on0xC8qk+DL0rHK5d7XGawU24AvnQ6YgI+zQwIa3TomKKJdiE+iNVzibN8s8P5ULQYq/6dI1jKgzZAxbnKVwnUKOGod1kjLtb6aVKLwpWQUmJANEXo8TyqBivAoacAnHXEO4KMq9avQRA14KFnNErU1Q=
