language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
- pip
- directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script: "./gradlew build"
env:
  global:
  - secure: qSNqGoDEv5v+2Ki4GAzeVPXmtqV65pjZ9aD/VzG9kuUXsiKJ2roLr/bzjJ/EbiYRXSq5LPMSYQgt3p3aLuexMOQCOD3mz9emxSS/0nkomNXA5cDQb+bonxfW6uZdFWZ6szqD587rrQzSWxc07AM13CX/g1LBHU4cT6EAhXpHjror5a7qrcFWloHSZXcW4PtF4zLwW4P4RrsEKGdUcQRM0N2CV0PMtgWh/4BVI/pongyH5NOXNl7hhu5T1N5uZQjYOV5LCKHIBOhUAbPPX5bZ8PEhXLodWKZ9trP6F1K8GkS3I/II7t3HD2+Ao5P7B5IpgBV9i8tVDl2pnog3I7+65sUONOjbMA2aRfLW/YcT6ZEqdH46d+HdqTcVlO5s1IuD+nkBQ6EjUpr/3LtHj5DrN/oLv+wgZRplg9ZDgskRSb1EvUZyUsQ/I01wglmBnVdbfvgiUrl4tc4GT8ZTt1ON5rUBXYgiT9Tw4rlz9UZVJ/jAdeGjhYXkPJMTemsjrhSemPMrzocgmmq3YDvuMv/LCGKVZxZ/04jE3d5RN5Fh7qYaI/xGy3RGk4ASofIQLbUYVz/c3U/hAmZLomrE2zdCmxB1oi1JNmNUp+MBPr8Df/7UaL9eW/3tY6IZnu2ANaV3nV/52sg1nRWjVc2fSzWiNk2I1gGfWNMsRv9Z7jsG4sg=
before_deploy:
- pip install --user awscli
deploy:
- provider: s3
  skip_cleanup: true
  region: eu-west-1
  bucket: latcraft-code
  local_dir: build/distributions
  acl: public_read
after_deploy:
- aws lambda update-function-code --function-name copy_contacts_from_event_brite_to_send_grid_function
  --s3-bucket latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name create_new_event_function --s3-bucket
  latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name get_stats_from_event_brite_function
  --s3-bucket latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name list_event_brite_venues_function
  --s3-bucket latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name list_suppressed_emails_function
  --s3-bucket latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name publish_campaign_on_send_grid_function
  --s3-bucket latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name publish_cards_on_s3_function --s3-bucket
  latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name publish_event_on_event_brite_function
  --s3-bucket latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name publish_event_on_lanyrd_function
  --s3-bucket latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name publish_event_on_twitter_function
  --s3-bucket latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name send_campaign_on_send_grid_function
  --s3-bucket latcraft-code --s3-key event-manager.zip
- aws lambda update-function-code --function-name craftbot_function --s3-bucket latcraft-code
  --s3-key event-manager.zip
notifications:
  slack:
    secure: fhCk8itykw1ZAEtYHI5bfd10Vp/gtByaOSq4BHD3T7EePSq8bLOOn6RNSXpL39TENvyPbfSsUxA9QbSDCskX/yEY4czIyKWPnCPDUeBnURuJYyXveB/WHL/zfXrDiy7N1AShBUfOEpnVuLRWx8D4r3B16FVtguCo4K2cA7H7o9iUpKsNUXM9SPHdthO6xrYokVJJ2dNteEpavvh+vTQYxcN71LRcnyeQc7LgjBxy66zlzsFiG42UJS1MpZBjnleCQnqijBt6ia7UB6BGKzZV98727M3pDZAg/vn8yA6ZB+qtF+K/ebBPHtGowKM+BVFU4JfvuRr97He/6SaowQXfToyypesswJpiAWClBWTDkEo2C8LxBonCjVJ80iaK7m9v+289Vqq3c4VZ+9VNjYMW7hqy6+Fl9ru/7turES/Fi5eI4H8e/OHKSQu2tEIkWAlyaw6TOJrgO42vD7teRLnM/5lYTJwFBI41zyJ/apD2FR2RjD5CN14Ub2VU5GEFBwQpFAbXItKLcTHNfoNyBizXLdYvkAKHvzodN4dhNATOVXA3RRqjrg54TaxzSpZlJ7QG+20olxkVrterNq41OF+p38nBQVvjOQ60XhZRduktohO9rovPlfOs8dNgpeJ2khYgWXw+6gyginLosNtY+piq4dpyxNEwGgn7oB1DL1UlSKI=
